### ISSUE TITLE
check if the failure with many character variants is a luaotfload bug or a fontloader problem. 

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/lua-font-pond#14]
See https://github.com/lualatex/luaotfload/issues/424

**Comment by u-fischer** [comment]
Looks like a luaotfload problem, it compiles in context now.

**Comment by zauguin** [comment]
Actually it's neither the fontloader nor luaotfload. LuaTeX requires font names to fit in 256 Bytes for compatibility with DVI files. ([The LuaTeX code](https://github.com/TeX-Live/luatex/blob/8113cb51f4899c4e81a363c1e10d63c673b100ac/source/texk/web2c/luatexdir/font/dofont.c#L84))

So if we want to support longer font names, we could get the LuaTeX team to lift this restriction at least for PDF output or we could change the font names after loading to something shorter.

@u-fischer Do we know if anyone is relying on correct fontnames in LaTeX?
Do you know what ConTeXt is doing here?

**Comment by u-fischer** [comment]
@zauguin  I think context is throwing away the features that make the font name too long. When I move +tlig at the end there is no longer a ligature in --.

**Comment by u-fischer** [comment]
seems to be resolved, see original issue.
